### ISSUE TITLE
MacBook9,1 EEEE Code and Board Type

### ISSUE THREAD

**Issue by Drfrag** [theracermaster/MacGen#5]
Please add this EEEE Code for Macbook9,1: 'H6KX'
And my Board Type is '601' and not '307'.
This were extracted from a MacBook9,1 Serial Number from Week 46 /2016 and Logic Board from week 44/2016.
And also found a new CCC code '4W'
I think it would be a good thing to generate Logic Board Week some Weeks before Mac Serial Number, like 1 to 4 weeks younger.

**Comment by al3xtjames** [comment]
Hmm, interesting. This isn't the first time that I've seen discrepancies in the board type value. Thanks for the data, I will update the script soon.

As for the week value, [`mg-mlb-serial` already generates a week number that is one before the serial week number](https://github.com/theracermaster/MacGen/blob/master/mg-mlb-serial#L93):

```sh
	## Logic boards are produced ~1 week before the system is complete
	local WW=$(($(decode_week_val "$serialY" "$serialW") - 1))
	if [ $gDebug -eq 1 ]; then
		print_debug "Manufacturing week (from serial number)" "$WW"
	fi
```

**Comment by Drfrag** [comment]
Thanks for showing that. 
Great work.
